export const menuArray = [
  { title: "Bachelors Veg Thali", subtext: "Plain Steam Rice + 1 Veg Sabji + Chatni + Dal", price: 119, veg: true, tags: ["full meal"] },
  { title: "Bachelors Fish Thali", subtext: "Plain Steam Rice + Katla Kalia + Chatni + Dal", price: 139, veg: false, tags: ["full meal"] },
  { title: "Bachelors Chicken Thali", subtext: "Plain Steam Rice + Chicken Kosha + Chatni + Dal", price: 149, veg: false, tags: ["full meal"] },
  { title: "Bachelors Mutton Thali", subtext: "Plain Steam Rice + Mutton Kosha + Chatni + Dal", price: 219, veg: false, tags: ["full meal"] },
  { title: "Bachelors Egg Thali", subtext: "Plain Steam Rice + Egg Curry/Kosha (1pc) + Chatni + Dal", price: 119, veg: false, tags: ["full meal"] },
  { title: "Bachelors Siddho Thali", subtext: "Plain Steam Rice + Aloo Siddho + Omlette + Chatni + Dal", price: 119, veg: true, tags: ["full meal"] },
  { title: "Luchi (4pcs) + Alur Dom", subtext: "", price: 149, veg: true, tags: ["snacks"] },
  { title: "Koraishutir Kachori (4pcs) + Alur Dom", subtext: "", price: 169, veg: true, tags: ["snacks"] },
  { title: "Radhaballavi (4pcs) + Alur Dom", subtext: "", price: 169, veg: true, tags: ["snacks"] },
  { title: "Luchi (4pcs) + Cholar Dal", subtext: "", price: 149, veg: true, tags: ["snacks"] },
  { title: "Koraishutir Kachori (4pcs) + Cholar Dal", subtext: "", price: 169, veg: true, tags: ["snacks"] },
  { title: "Radhaballavi (4pcs) + Cholar Dal", subtext: "", price: 169, veg: true, tags: ["snacks"] },
  { title: "Gobindo Bhog Chal er Khicudi + Begun Bhaja (2pcs)", subtext: "", price: 149, veg: true, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Egg Torka", subtext: "", price: 159, veg: false, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Chicken Torka", subtext: "", price: 179, veg: false, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Egg Chicken Torka", subtext: "", price: 179, veg: false, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Begun Bhaja (2pcs)", subtext: "", price: 119, veg: true, tags: ["snacks"] },
  { title: "Aloo Paratha (1pc) + Curd + Pickle", subtext: "", price: 119, veg: true, tags: ["snacks"] },
  { title: "Gobi Paratha (1pc) + Curd + Pickle", subtext: "", price: 119, veg: true, tags: ["snacks"] },
  { title: "Keema Paratha (1pc) + Curd + Pickle", subtext: "", price: 129, veg: false, tags: ["snacks"] },
  { title: "Bread Omlette (2pcs)", subtext: "", price: 99, veg: false, tags: ["snacks"] },
  { title: "Toasted Bread (3pcs) + Egg Bhurji (2pcs)", subtext: "", price: 99, veg: false, tags: ["snacks"] },
  { title: "Mini English Breakfast", subtext: "Bread Toast (3pcs) + Boiled Egg (1pc) + Chicken Sausage (2pcs) + Sprouts Chat + Butter", price: 199, veg: false, tags: ["full meal"] },
  { title: "Sprouts Chat", subtext: "", price: 99, veg: true, tags: ["snacks"] },
  { title: "Veg Clear Soup", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Veg Hot & Sour Soup", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Manchow Soup", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Tomato Soup", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Sweet Corn Soup", subtext: "", price: 149, veg: true, tags: ["snacks"] },
  { title: "Corn Mashroom Soup", subtext: "", price: 149, veg: true, tags: ["snacks"] },
  { title: "Clear Broccoli Soup", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Chicken Clear Soup", subtext: "", price: 199, veg: false, tags: ["snacks"] },
  { title: "Chicken Hot & Sour Soup", subtext: "", price: 199, veg: false, tags: ["snacks"] },
  { title: "Chicken Mushroom Soup", subtext: "", price: 199, veg: false, tags: ["snacks"] },
  { title: "Mutton Paya Soup", subtext: "", price: 199, veg: false, tags: ["snacks"] },
  { title: "Mixed Soup", subtext: "", price: 229, veg: false, tags: ["snacks"] },
  { title: "Veg Chop (2pcs)", subtext: "Mixed Vegetables Smashed And Prepared With Bread Crumbs", price: 99, veg: true, tags: ["snacks"] },
  { title: "Bhetki Fish Fry (1pc)", subtext: "Bhetki Fish Fillet Fried With Bread Crumbs", price: 229, veg: false, tags: ["snacks"] },
  { title: "Chicken Cutlet (1pc)", subtext: "Boneless Chicken Smashed And Prepared With Bread Crumbs", price: 199, veg: false, tags: ["snacks"] },
  { title: "Fish Finger (6pcs)", subtext: "Bhetki Fish Fillet Fried With Bread Crumbs As Fingers", price: 229, veg: false, tags: ["snacks"] },
  { title: "Fish Chop (2pcs)", subtext: "Bhetki Boneless Fish Smashed And Prepared With Bread Crumbs", price: 219, veg: false, tags: ["snacks"] },
  { title: "Beguni (4pcs)", subtext: "", price: 119, veg: true, tags: ["snacks"] },
  { title: "Fish Kabiraji", subtext: "Kabiraji Prepared With Bhetki Fish Fry", price: 239, veg: false, tags: ["snacks"] },
  { title: "Chingri Chop (2pcs)", subtext: "Chingri (prawns) Smashed With Potato And Prepared With Bread Crumbs", price: 199, veg: false, tags: ["snacks"] },
  { title: "Chicken Pakora (6pcs)", subtext: "", price: 199, veg: false, tags: ["snacks"] },
  { title: "Egg Devil Chicken (1pc)", subtext: "", price: 119, veg: false, tags: ["snacks"] },
  { title: "Egg Devil Potato (2pcs)", subtext: "", price: 129, veg: false, tags: ["snacks"] },
  { title: "Egg Mughlai Paratha With Alur Dom", subtext: "", price: 159, veg: false, tags: ["snacks"] },
  { title: "Chicken Mughlai Paratha With Alur Dom", subtext: "", price: 179, veg: false, tags: ["snacks"] },
  { title: "Posto Bora (2pcs)", subtext: "", price: 189, veg: true, tags: ["snacks"] },
  { title: "Mochar Chop (2pcs)", subtext: "", price: 149, veg: true, tags: ["snacks"] },
  { title: "King Fish/Surmai Rava Fish Fry (2pcs)", subtext: "", price: 399, veg: false, tags: ["snacks"] },
  { title: "Bhaja Moong Dal", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Narikel Diye Cholar Dal", subtext: "", price: 129, veg: true, tags: ["snacks"] },
  { title: "Shukto", subtext: "", price: 169, veg: true, tags: ["full meal"] },
  { title: "Aloo Potol Dalna", subtext: "", price: 169, veg: true, tags: ["full meal"] },
  { title: "Aloo Fulkopir Dalna", subtext: "", price: 169, veg: true, tags: ["full meal"] },
  { title: "Chanar Dalna", subtext: "", price: 229, veg: true, tags: ["full meal"] },
  { title: "Chanar Kalia", subtext: "", price: 229, veg: true, tags: ["full meal"] },
  { title: "Aloo Posto", subtext: "", price: 169, veg: true, tags: ["full meal"] },
  { title: "Potol Posto", subtext: "", price: 199, veg: true, tags: ["full meal"] },
  { title: "Jhinge Aloo Posto", subtext: "", price: 199, veg: true, tags: ["full meal"] },
  { title: "Alur Dom / Dum Aloo", subtext: "", price: 149, veg: true, tags: ["full meal"] },
  { title: "Echor Torkari", subtext: "", price: 169, veg: true, tags: ["full meal"] },
  { title: "Macher Matha Diye Moong Dal", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Muri Ghonto", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Katla Kalia (1pc)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Katla Shorse (1pc)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Doi Katla (1pc)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Jeere diye Katla Macher Jhol (1pc)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Chingri Malai Curry (2pcs)", subtext: "", price: 319, veg: false, tags: ["full meal"] },
  { title: "Chingri Bhapa (2pcs)", subtext: "", price: 319, veg: false, tags: ["full meal"] },
  { title: "Echor Chingri", subtext: "", price: 319, veg: false, tags: ["full meal"] },
  { title: "Ilish Shorse (1pc)", subtext: "", price: 549, veg: false, tags: ["full meal"] },
  { title: "Ilish Bhapa (1pc)", subtext: "", price: 549, veg: false, tags: ["full meal"] },
  { title: "Ilish Bhaja (1pc)", subtext: "", price: 549, veg: false, tags: ["full meal"] },
  { title: "Ilish Macher er Jhol (1pc)", subtext: "", price: 549, veg: false, tags: ["full meal"] },
  { title: "Chicken Kosha (4 pcs)", subtext: "", price: 249, veg: false, tags: ["full meal"] },
  { title: "Aloo Diye Murgir Jhol (4 pcs)", subtext: "", price: 249, veg: false, tags: ["full meal"] },
  { title: "Mutton Kosha (4 pcs)", subtext: "", price: 369, veg: false, tags: ["full meal"] },
  { title: "Aloo Diye Mutton Jhol (4 pcs)", subtext: "", price: 369, veg: false, tags: ["full meal"] },
  { title: "Chicken Dakbunglow (4 pcs)", subtext: "", price: 279, veg: false, tags: ["full meal"] },
  { title: "Golbari Chicken Kosha (4 pcs)", subtext: "", price: 299, veg: false, tags: ["full meal"] },
  { title: "Mutton Dakbunglow (4 pcs)", subtext: "", price: 389, veg: false, tags: ["full meal"] },
  { title: "Golbari Mutton Kosha (4 pcs)", subtext: "", price: 399, veg: false, tags: ["full meal"] },
  { title: "Egg Curry with Alu (2 pcs)", subtext: "", price: 149, veg: false, tags: ["full meal"] },
  { title: "Egg Kosha (2 pcs)", subtext: "", price: 149, veg: false, tags: ["full meal"] },
  { title: "Charubon's Special Egg Biryani", subtext: "Biryani Along With 2 Eggs & 1 Aloo + Raita", price: 189, veg: false, tags: ["full meal"] },
  { title: "Charubon's Special Chicken Biryani", subtext: "Biryani Along With 1 Chicken Leg Piece, 1 Egg & 1 Aloo + Raita", price: 269, veg: false, tags: ["full meal"] },
  { title: "Charubon's Special Mutton Biryani", subtext: "Biryani Along With 1 Mutton Piece, 1 Egg & 1 Aloo + Raita", price: 369, veg: false, tags: ["full meal"] },
  { title: "Luchi (4pcs) + Chicken Kosha (2pcs)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Koraishutir Kachori (4pcs) + Chicken Kosha (2pcs)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Radhaballavi (4pcs) + Chicken Kosha (2pcs)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Basanti Pulao + Chicken Kosha (2pcs)", subtext: "", price: 249, veg: false, tags: ["full meal"] },
  { title: "Basanti Pulao + Mutton Kosha (2pcs)", subtext: "", price: 349, veg: false, tags: ["full meal"] },
  { title: "Basanti Pulao + Mutter Paneer", subtext: "", price: 249, veg: true, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Chicken Kosha (2pcs)", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Mutton Kosha (2pcs)", subtext: "", price: 249, veg: false, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Mutter Paneer", subtext: "", price: 199, veg: true, tags: ["full meal"] },
  { title: "Phulka Roti (3pcs) + Chicken Bharta", subtext: "", price: 199, veg: false, tags: ["full meal"] },
  { title: "Veg Thali", subtext: "Basmati Rice + Dal + 2 Veg Sabji + Chatni + Aloo Jhuri Bhaja/Bhaja + Mishti/Misti Doi + Salad", price: 229, veg: true, tags: ["full meal"] },
  { title: "Katla Thali", subtext: "Basmati Rice + Katla Kalia + 1 Veg Sabji + Dal + Chatni + Aloo Jhuri Bhaja + Mishti/Misti Doi + Salad", price: 289, veg: false, tags: ["full meal"] },
  { title: "Chicken Thali", subtext: "Basmati Rice + Chicken Kosha + 1 Veg Sabji + Dal + Chatni + Aloo Jhuri Bhaja + Mishti/Misti Doi + Salad", price: 289, veg: false, tags: ["full meal"] },
  { title: "Mutton Thali", subtext: "Basmati Rice + Mutton Kosha + 1 Veg Sabji + Dal + Chatni + Aloo Jhuri Bhaja + Mishti/Misti Doi + Salad", price: 389, veg: false, tags: ["full meal"] },
  { title: "Egg Thali", subtext: "Basmati Rice + Egg Curry + 1 Veg Sabji + Dal + Chatni + Aloo Jhuri Bhaja + Mishti/Misti Doi + Salad", price: 229, veg: false, tags: ["full meal"] },
  { title: "Ilish Thali", subtext: "Basmati Rice + Ilish Sorse + 1 Veg Sabji + Dal + Chatni + Aloo Jhuri Bhaja + Mishti/Misti Doi + Salad", price: 599, veg: false, tags: ["full meal"] },
];
